-- sum :: [Int] %1-> Int
-- sum []     = 0
-- sum (x:xs) = x + sum xs

-- f :: [Int] %1-> [Int] %1-> Int
-- f xs ys = sum (xs ++ ys) ++ sum ys
--
--
-- TODO:
--  - Unrestricted
--  - The list thing above
